alias c='cd'
alias ..='cd ..'
alias l='ls -alh'
alias gs='git status'
alias gp='git pull'
alias ga='git add'
alias gc='git commit --verbose'
alias home='cd ~'
alias dt='cd ~/Desktop'
alias gf='git fetch'
alias gl='git log --pretty=oneline'
alias gd='git diff'
alias v='vim'
PS1="\e[1;32m\u\e[1;33m@\e[1;31m\h\e[0m[\t]:\w\n\$ "
LS_COLORS='di=01;36:ln=00;95'
